trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "develop"

variables:
  - group: SHARE

jobs:
  - job: ReviewPullRequest
    displayName: "Review Pull Request"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        displayName: "Checkout HEAD branch"
        fetchDepth: 0

      - script: |
          git fetch origin $(System.PullRequest.TargetBranch)
          git fetch origin $(System.PullRequest.SourceBranch)
        displayName: "Fetch base and source branch"

      - task: UseDotNet@2
        displayName: "Setup .NET"
        inputs:
          packageType: "sdk"
          version: "6.x"

      - script: |
          echo '{"Comments": "テスト"}' > result.json
          repository_id=$(curl -s -H "Authorization: token $(System.AccessToken)" https://api.github.com/repos/$(Build.Repository.Name) | jq '.id')
          echo "$repository_id"
          dotnet run --project ./tools/CommentPoster "result.json" "$(Build.Repository.Name)" "$repository_id" "$(System.PullRequest.PullRequestId)"
        env:
          GITHUB_TOKEN: $(System.AccessToken)

      - script: |
          dotnet run --project ./tools/PullRequestReviewer "refs/remotes/origin/$(System.PullRequest.TargetBranch)" "refs/remotes/origin/$(System.PullRequest.SourceBranch)"
        displayName: "Run review script"
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)

      - script: |
          sudo apt-get install -y jq
        displayName: "Install jq"

      - script: |
          result=$(jq -r '.Comments' result.json)
          escaped_result=$(echo "$result" | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/%0A/g')
          echo "##vso[task.setvariable variable=review.result]$escaped_result"
        displayName: "Format review comments"

      - task: GitHubComment@0
        displayName: "Post review comments"
        inputs:
          gitHubConnection: "$(GITHUB_CONNECTION_NAME)"
          repositoryName: "$(Build.Repository.Name)"
          comment: |
            $(review.result)