trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "develop"

variables:
  - group: SHARE

jobs:
  - job: ReviewPullRequest
    displayName: "Review Pull Request"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        displayName: "Checkout HEAD branch"
        fetchDepth: 0

      - script: |
          git fetch origin $(System.PullRequest.TargetBranch)
          git fetch origin $(System.PullRequest.SourceBranch)
        displayName: "Fetch base and source branch"

      - task: UseDotNet@2
        displayName: "Setup .NET"
        inputs:
          packageType: "sdk"
          version: "6.x"

      - script: |
          dotnet run --project ./tools/PullRequestReviewer "refs/remotes/origin/$(System.PullRequest.TargetBranch)" "refs/remotes/origin/$(System.PullRequest.SourceBranch)"
        displayName: "Run review script"
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)

      - script: |
          sudo apt-get install -y jq
        displayName: "Install jq"

      - script: |
          result=$(jq -r '.Comments' result.json)
          escaped_result=$(printf '%s' "$COMMENTS" | awk '{gsub(/\r?\n/,"%0A")}1')
          echo "##vso[task.setvariable variable=review.result]$escaped_result"

      - task: GitHubComment@0
        displayName: "Post review comments"
        inputs:
          gitHubConnection: "$(GITHUB_CONNECTION_NAME)"
          repositoryName: "$(Build.Repository.Name)"
          comment: |
            ```
            $(review.result)
            ```
