name: Review Pull Request

on:
  pull_request:
    branches:
      - "develop"

jobs:
  review-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Run review script
        run: dotnet run --project ./tools/PullRequestReviewer "refs/heads/${{ github.head_ref }}" "refs/remotes/origin/${{ github.base_ref }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Post review comment
        run: |
          comment="$(cat review.env | tr -d '\000-\011\013\014\016-\037')"
          pr_number=$(echo ${{ github.event.pull_request.number }} | xargs)
          comment_url="${{ github.event.pull_request.comments_url }}"
          auth_header="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          content_type_header="Content-Type: application/json"
          payload=$(echo '{ "body": "'"${comment//\"/\\\"}"'" }' | jq -c .)
          curl -X POST -H "${auth_header}" -H "${content_type_header}" --data "${payload}" "${comment_url}"
        if: ${{ github.event_name == 'pull_request' }}