name: Review Pull Request

on:
  pull_request:
    branches:
      - "develop"

jobs:
  detect-added-classes-and-interfaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Run script
        run: dotnet run --project ./tools/PullRequestReviewer "${{ github.base_ref }}"
